name: TestWorker
on:
  push:

jobs:
  setup-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3


      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Cache Docker-compose
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-

      - name: Build Docker images
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          push: false
          load: true
          builder: ${{ steps.buildx.outputs.name }}
          tags: ducthinh1606/test-cache-docker:latest
          file: ./Dockerfile
          context: ./


      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Run docker-compose
        run: docker-compose up -d --no-build

      - name: Access backend container
        run: docker-compose exec -T backend sh
